# This yaml file is for loading local database, server port, disable eureka and set jwt-rest-service endpoint
server:
  port: 8082

POSTGRES_USERNAME: test
POSTGRES_PASSWORD: test
POSTGRES_DBNAME: application
POSTGRES_SERVICE: localhost:5432
DB_SSLMODE: disable

eureka:
  client:
    enabled: false

# jwt-rest-service on port 8081 local server
jwt-rest-service-public-key-id: http://localhost:8081/jwts/publickeys/{keyId}
jwt-rest-service-accesstoken: http://localhost:8081/jwts/accesstoken
hmacKeyEndpoint: http://localhost:8081/jwts/hmackey/

hmackeys:
  - app: '{"clientId":"authentication-rest-service","name":"authentication"}'
  - app: '{"clientId":"account-rest-service","name":"HmacMD5","secretKey":"mysecret","active":true, "isNew": true}'
  - app: '{"clientId":"user-rest-service","hmacMD5Algorithm":"HmacMD5","secretKey":"mysecret","active":true, "isNew": true}'

hmackey:
  clientId: application-rest-service
  hmacMD5Algorithm: HmacMD5
  secretKey: mysecret
