# This yaml file is for loading local database, server port, disable eureka and set jwt-rest-service endpoint
server:
  port: 8082

POSTGRES_USERNAME: test
POSTGRES_PASSWORD: test
POSTGRES_DBNAME: application
POSTGRES_SERVICE: localhost:5432
DB_SSLMODE: disable

eureka:
  client:
    enabled: false

JWT_REST_SERVICE: http://localhost:8081

HMAC_CLIENTID: application-rest-service
HMAC_ALGORITHM: HmacMD5
HMAC_SECRET: mysecret