logging:
  level:
    root: error
    me:
      sonam: debug
info:
  app:
    name: Springboot me.sonam.account.Application
    description: This is a Springboot application
    version: 1.0.0

management:
  endpoint:
    health:
      show-details: always

server:
  port: 8080

spring:
  r2dbc:
    url: r2dbc:postgresql://${POSTGRES_SERVICE}/${POSTGRES_DBNAME}
    username: ${POSTGRES_USERNAME}
    password: ${POSTGRES_PASSWORD}
    properties:
      sslMode: ${DB_SSLMODE}

eureka:
  client:
    serviceUrl:
      defaultZone: https://${EUREKA_USER}:${EUREKA_PASSWORD}@discovery-service.sonam.cloud/eureka

jwt-rest-service-public-key-id: ${jwt-rest-service-public-key-id}
jwt-rest-service-accesstoken: ${jwt-rest-service-accesstoken}


permitpath:
  - path: /api/health/*

jwtrequest:
  - in:  /applications
    out: /jwts/hmackey/(.)*
    jwt: forward